index.js

enable the possibility to run all tests in sequence on windows

fix: test sequence on windows

---

errors.js
index.js
port.js

For disconnection handling see changes in port.js
Other changes are for simplifying errors.

Improve disconnection handling

---

index.js
test/testBus.js

Client bus automatic reconnection.

feat: reconnect

---

index.js

fix: Make code easier to read and facilitate debugging.

fix: cleanup

---

port.js

more thorough checks about $meta and add message to queue after the cb has been assigned

fix: more thorough checks

---

port.js

add timeTaken tagged measurement for all ports

fix: add timeTaken tagged measurement for all ports

---

port.js

pipeReverse latency and timeTaken counters

pipeReverse latency and timeTaken counters

---

port.js

add hostname to performance measurements for uniqueness

fix: add hostname to performance measurements for uniqueness

---

port.js

feat: port events implementation

---

port.js

fix: stop ports properly

---

index.js

feat: public api

---

errors.js
index.js

fix: pass logger to utError

---

swagger/index.js

apply transformer when converting joi respones too

fix: convert joi response schemas too

---

README.md

docs: document transports

---

README.md
serviceBus.js

pass $applyMeta.auth to $metaBefore and $metaAfter

pass $applyMeta.auth to $metaBefore and $metaAfter

---

.vscode/launch.json
mle.js
test/jsonrpc.test.js

identical check before encrypting as the one before decrypting

fix: identical check before encrypting as the one before decrypting

---

serviceBus.js

don't try to set undefined value in cache

fix: don't attempt setting undefined value in cache

---

jsonrpc.js

Check whether serviceBus.api is enabled before collecting data from internal services

fix: check whether serviceBus.api is enabled

---

.vscode/settings.json
jwt.js

possibility to encode arbitrary claims in jwt token

feat: possibility to encode arbitrary claims in jwt token

---

mle.js

encrypt only error instead of the whole message when encountering request validation error

fix: encrypt only error instead of the whole message

---

gateway.js
jsonrpc.js
test/mle.test.js

handle incorrect gateway url configuration

fix: handle incorrect gateway url configuration

---

broker.js
jsonrpc.js
package.json

display impl version in api docs

fix: display impl version in api docs

---

jsonrpc.js

extend bus.jsonRpcHttp error details

fix: extend bus.jsonRpcHttp error details

---

jsonrpc.js

fix: improve error logging

---

.vscode/settings.json
gateway.js
package.json
tap-snapshots/test-mle.test.js-TAP.test.js
test/mle.test.js
test/tests.js

don't rely on the fact that access_token is JWT

don't rely on the fact that access_token is JWT

---

jsonrpc.js

fix: generate default value for meta.forward['x-b3-traceid']

fix: generate default value for meta.forward['x-b3-traceid']

---

jsonrpc.js
serviceBus.js

pass x-ut-stack header to .forward

feat: pass x-ut-stack header to .forward

---

gateway.js
jsonrpc.js

don't pack errors received in gateway

fix: don't pack errors received in gateway

---

jsonrpc.js

allow defining gateways per namespace

fix: allow defining gateways per namespace

---

jsonrpc.js

add debug info in brokerMethod error

fix: add debug info in brokerMethod error

---

jsonrpc.js
mle.js

fix: mle error formatting

---

mle.js

serialize writable error properties only

fix: serialize writable error properties only

---

jsonrpc.js

add auth information in well-known/mle result

fix: add auth information in well-known/mle result

---

.vscode/launch.json
jose.js
test/jose.test.js

Compact decrypt

---

jsonrpc.js

pass checkAuth to utApi.rpcRoutes

fix: pass checkAuth to utApi.rpcRoutes

---

jose.js

sign/encrypt serialization options

fix: signEncrypt serialization options

---

mle.js

fix: rest mle

---

mle.js

fix: rest mle response

---

hemera.js
mle.js

fix: disable mle per api

---

README.md
jsonrpc.js

socket.onRequest pre hooks configuration

fix: socket.pre hooks configuration

---

jsonrpc.js

fix: rename meta -> preMeta

---

gateway.js
test/bus.test.js

test: handle empty login result

---

jsonrpc.js
jwt.js
oidc.js

fix: ut-bus-asset-viewAs

---

oidc.js

e.g: `checkAuth('cbs.%', permissions, true)`

feat: fuzzy permission check

---

.vscode/settings.json
jsonrpc.js

possibility to clear HTTP cookie via response.unstate

fix: possibility to clear HTTP cookie via response.unstate

---

README.md
jsonrpc.js
tap-snapshots/test/jsonrpc.test.js.test.cjs
test/jsonrpc.test.js
test/tests.js

Error fields visibility cofiguration

fix: Error fields visibility cofiguration

---

jsonrpc.js
mle.js

format error in mle plugin in accordance to formatError configuration

fix: format error in mle plugin

---

mle.js

support non jsonrpc requests properly

fix: support non jsonrpc requests properly

---

jsonrpc.js

Related to:
https://github.com/softwaregroup-bg/ut-port-http/pull/51/files
https://github.com/softwaregroup-bg/ut-browser/pull/3/files

feat(CBI-999): browser/server ut version
